replicaCount: 1

# Specify target ns here otherwise .Release.Namespace will be used
#namespace: target_namespace_here

image:
  repository: ghcr.io/rjbrown57/binman
  pullPolicy: IfNotPresent
  # Overrides the image tag whose default is the chart appVersion.
  tag: "latest"

imagePullSecrets: []
nameOverride: ""
fullnameOverride: ""

securityContext:
  capabilities:
    drop:
    - ALL
  readOnlyRootFilesystem: true
  runAsNonRoot: true
  runAsUser: 1000

resources: {}
  # limits:
  #   cpu: 100m
  #   memory: 128Mi
  # requests:
  #   cpu: 100m
  #   memory: 128Mi

binmanConfig:
  releasePath: /binMan/
  configPath: /config
  configName: config.yaml


# Prep secret with kubectl create secret generic binmangh --from-literal=value='secrethere'
auth:
  enabled: true
  secrets:
  - name: binmangh
    envVar: GH_TOKEN
    key: value


service:
  port: 9091

pvc:
  enabled: false
  storageClassName: standard 
  storage: 1Gi
